# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  ARM_PASS: $(adminPass)

trigger:
- none
pool:
  name: az400m05l05a-pool
  demands:
  - agent.name -equals az400m05-vm0

steps:
- task: CopyFiles@2
  inputs:
      SourceFolder: '101-webapp-linux-managed-mysql'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azurepass'
    subscriptionId: 'a8ce7e3c-0da0-4a05-9c9c-a7c5c44a2fab'
    action: 'Create or update resource group'
    resourceGroupName: 'ARMPipelinesLAMP-rg'
    location: 'eastasia'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.parameters.json'
    overrideParameters: '-siteName $(siteName) -administratorLogin $(adminUser) -administratorLoginPassword $(ARM_PASS)'
    deploymentMode: 'Incremental' 